# Site settings
title: Nyan Win
email: promise286@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/veve" # the subpath of your site, e.g. /blog/
url: "http://pyaesone17.github.io/veve/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
paginate: 2
paginate_path: "/archives/page/:num"

# Build settings
markdown: kramdown
